apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment #user defined eg nginx-sukumawiki
spec:
  selector: #selects the pods that share the same label 
    matchLabels:
      app: nginx-dev05 #all pods created will have a label of nginx 
  
  replicas: 2

  template:
    metadata:
      labels:
        app: nginx-dev05
  
    spec:
      containers:
      - name: nginx-dev05
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
