apiVersion: v1
kind: Service
metadata:
  name: nginx-service #can be any name - it will service some pods 
spec:
  type: LoadBalancer #loadbalancer created so as to expose the service to external traffic
  selector:
    app: nginx-dev05
  ports:
  - port: 80 #service port
    targetPort: 80 #port defined in the deployment
    nodePort: 30000 #range is from 30000 to 32000
#need to give a node port to expose 